# Generated by Django 6.0.4 on 2026-04-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='course',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddField(
            model_name='registration',
            name='plan',
            field=models.CharField(default='Basic', max_length=50),
        ),
    ]
