# Generated by Django 5.2.11 on 2026-05-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0005_event_alter_contributor_id_alter_demorequest_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("author", models.CharField(default="GyanSutra Team", max_length=255)),
                ("content", models.TextField()),
                ("excerpt", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("category", models.CharField(default="General", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
