# Generated by Django 5.2.11 on 2026-05-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0006_blogpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ambassador",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("college", models.CharField(max_length=255)),
                ("year", models.CharField(max_length=50)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
